#!/bin/bash
cpan -i Getopt::Long
cpan -i Text::CSV
cpan -i Math::Round
cpan -i WebService::Discord::Webhook
cpan -i String::Scanf
cpan -i Cwd
cpan -i Storable
cpan -i UI::Dialog
cpan -i Term::ReadKey
cpan -i Term::ANSIScreen
cpan -i Proc::ProcessTable
cpan -i Number::Bytes::Human
cpan -i POSIX
cpan -i Email::Simple
cpan -i Email::Sender::Simple

exit 0
